server:
  port: 8081

spring:
  application:
    name: data-label-system
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

admin:
  username: admin
  password: admin123
  name: 系统管理员
